config/routes.rb
Rails.application.routes.draw do
  resources :file_uploads, only: [:create, :show] do
    get :download, on: :member
  end
  root 'file_uploads#index'
end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base
  do_not_validate_attachment_file_type :secure_file
  has_attached_file :secure_file,
    url: ":s3_domain_url",
    path: 'secure_files/:id/:style_:basename_:hash.:extension',
    storage: :s3,
    bucket: ENV['S3_BUCKET'],
    s3_credentials: {
      access_key_id: ENV['S3_KEY'],
      secret_access_key: ENV['S3_SECRET']
    },
    s3_protocol: "https",
    hash_secret: 'semiuniquehash',
    s3_permissions: :private


  def encode!
    format = File.extname(secure_file_file_name)
    response = Zencoder::Job.create({
      input: self.secure_file.expiring_url,
      output: [{
        label: 'transcoded',
        url: self.secure_file.url(:transcoded)
      }]
    })
    update(zencoder_id: response.body['id'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  def show
    @file = FileUpload.find(params[:id])
    response = Zencoder::Job.progress(@file.zencoder_id)
    @status = response.body['state']
  end

  def create
    @file = FileUpload.create(file_upload_params)
    @file.encode!

    redirect_to root_path, notice: 'File uploaded'
  end

  def download
    @file_upload = FileUpload.find(params[:id])
    # Redirect here if user is not permitted to download. Otherwise redirect
    # the client to a signed, expiring url.
    # EXAMPLE: redirect_to :back && return unless can? :view, @file_upload
    redirect_to @file_upload.secure_file.expiring_url(10)
  end

  private

  def file_upload_params
    params.permit(:secure_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/file_uploads/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12'>
      <%= form_for(FileUpload.new) do |f| %>
        <%= f.file_field :secure_file, name: 'secure_file' %>
        <%= f.submit 'Upload' %>
      <% end %>
    </div>
  </div>

  <% FileUpload.all.each do |upload| %>
    <div class='row'>
      <div class='col-xs-12'>
        <%= "Upload #{upload.id}" %> |
        <%= link_to 'Download', download_file_upload_path(upload), target: '_blank' %>
        <%= link_to 'View', file_upload_path(upload) %>
      </div>
    </div>
  <% end %>
</div>

app/views/file_uploads/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12'>
      <% if @status == 'finished' %>
        <video id="example_video_1" class="video-js vjs-default-skin"
               controls preload="auto" width="640" height="264"
               poster="http://video-js.zencoder.com/oceans-clip.png"
               data-setup='{"example_option":true}'>
          <source src="<%= @file.secure_file.expiring_url(3600, :transcoded) %>" type='video/webm' />
          <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
        </video>
      <% else %>
        Transcoding, please visit again
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  <% elsif alert %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CdnDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/alerts' %>
<%= yield %>

</body>
</html>